#!/bin/bash

DATA_FILE="data.json"

if [ ! -f "$DATA_FILE" ]; then
    echo "Error: $DATA_FILE not found. Please run apiAutomation-0x00 first."
    exit 1
fi

name=$(jq -r '.name' "$DATA_FILE" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
type=$(jq -r '.types[0].type.name' "$DATA_FILE" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
formatted_weight=$(jq -r '.weight' "$DATA_FILE" | awk '{printf "%.0f", $1/10}')
formatted_height=$(jq -r '.height' "$DATA_FILE" | awk '{printf "%.1f", $1/10}')

name=$(echo "$name" | sed 's/.*/\u&/')
type=$(echo "$type" | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."